### ISSUE TITLE
Fishing System 🎣

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/fishmonger#6]
> the mechanic core of the game: the player runs around, uses his fishing rod to catch fish. 🐟

In order for this mechanic to be engaging, we decided to go for an action-based approach, instead of a wait-and-see approach (like in Stardew Valley). The gameplay should look as follows:

1. the player goes near water to see fish swimming in there
2. the player presses a key to throw the fishing rod
3. the fishing rod has a range - a fish has been caught if the fish crosses the "shooting" line of the rod
4. the fish is added to the inventory

## Tasks

* [ ] implement fish spawn mechanism
* [ ] implement fish movement logic based on A*
* [ ] implement inventory system (see issue #11 )
* [ ] implement catching mechanic
* [ ] implement fishing rod animation/spriting
